import { createStore } from "vuex";

export default createStore({
  state: {
    designs: [
      {
        id: 1,
        src: require("@/assets/designs/designs-1.jpg"),
        srcTwo: require("@/assets/designs/designs-1-2.jpg"),
        title: "Resturant interior at a daytime",
        category: "Resturant",
        link: "resurant-interior-at-a-daytime",
      },
      {
        id: 2,
        src: require("@/assets/designs/designs-2.jpg"),
        srcTwo: require("@/assets/designs/designs-2-2.jpg"),
        title: "Modern Dinning Room",
        category: "Kitchen",
        link: "moder-dinning-room",
      },
      {
        id: 3,
        src: require("@/assets/designs/designs-3.jpg"),
        srcTwo: require("@/assets/designs/designs-3-2.jpg"),
        title: "Modern Office Reception",
        category: "Office",
        link: "modern-office-reception",
      },
      {
        id: 4,
        src: require("@/assets/designs/designs-4.jpg"),
        srcTwo: require("@/assets/designs/designs-4-2.jpg"),
        title: "Creative Work Place Design",
        category: "Office",
        link: "creative-work-place-design",
      },
      {
        id: 5,
        src: require("@/assets/designs/designs-5.jpg"),
        srcTwo: require("@/assets/designs/designs-5-2.jpg"),
        title: "Luxury House Kitchen",
        category: "Kitchen",
        link: "luxury-house-kitchen",
      },
      {
        id: 6,
        src: require("@/assets/designs/designs-6.jpg"),
        srcTwo: require("@/assets/designs/designs-6-2.jpg"),
        title: "Modern House Kitchen",
        category: "Kitchen",
        link: "modern-house-kitchen",
      },
      {
        id: 7,
        src: require("@/assets/designs/designs-7.jpg"),
        srcTwo: require("@/assets/designs/designs-7-2.jpg"),
        title: "Master Hall Interior",
        category: "House",
        link: "master-hall-interior",
      },
      {
        id: 8,
        src: require("@/assets/designs/designs-8.jpg"),
        srcTwo: require("@/assets/designs/designs-8-2.jpg"),
        title: "Beautiful Luxury Bedroom",
        category: "Bedroom",
        link: "beatiful-luxury-bedroom",
      },
      {
        id: 9,
        src: require("@/assets/designs/designs-9.jpg"),
        srcTwo: require("@/assets/designs/designs-9-2.jpg"),
        title: "Luxury Living Room",
        category: "House",
        link: "luxury-living-room",
      },
    ],
    blogs: [
      {
        id: 1,
        srcOne: require("@/assets/blog/blog-3.jpg"),
        srcTwo: require("@/assets/blog/blog-3-2.jpg"),
        date: "Nov 12, 2023",
        title: "Tips For Decorating with Textures and Fabrics",
        link: "tips-for-decorating-with-textures-and-fabrics",
        para: "Handsome met debating sir dwelling age material. As style lived he worse dried.",
      },
      {
        id: 2,
        srcOne: require("@/assets/blog/blog-2.jpg"),
        srcTwo: require("@/assets/blog/blog-2-2.jpg"),
        date: "Dec 5, 2023",
        title: "Creative Storage and Design Solutions",
        link: "creative-storage-and-design-solutions",
        para: "Arrived off she elderly beloved him affixed noisier yet. Course regard to up he hardly.",
      },
      {
        id: 3,
        srcOne: require("@/assets/blog/blog-1.jpg"),
        srcTwo: require("@/assets/blog/blog-1-2.jpg"),
        date: "May 6, 2023",
        title: "Easy and Affordable Projects to Transform your Space",
        link: "easy-and-affordable-projects-to-transform-your-space",
        para: "Unaffected at ye of compliment alteration to. Place voice no arises along to.",
      },
    ],
    allBlogs: [
      {
        id: 1,
        srcOne: require("@/assets/blog/blog-1.jpg"),
        srcTwo: require("@/assets/blog/blog-1-2.jpg"),
        date: "Nov 12, 2023",
        title: "Tips For Decorating with Textures and Fabrics",
        link: "tips-for-decorating-with-textures-and-fabrics",
        para: "Handsome met debating sir dwelling age material. As style lived he worse dried.",
      },
      {
        id: 2,
        srcOne: require("@/assets/blog/blog-2.jpg"),
        srcTwo: require("@/assets/blog/blog-2-2.jpg"),
        date: "Dec 5, 2023",
        title: "Creative Storage And Smart Design Solutions",
        link: "creative-storage-and-design-solutions",
        para: "Arrived off she elderly beloved him affixed noisier yet. Course regard to up he hardly.",
      },
      {
        id: 3,
        srcOne: require("@/assets/blog/blog-3.jpg"),
        srcTwo: require("@/assets/blog/blog-3-2.jpg"),
        date: "Jan 3, 2023",
        title: "Easy and Affordable Projects to Transform your Space",
        link: "easy-and-affordable-projects-to-transform-your-space",
        para: "Unaffected at ye of compliment alteration to. Place voice no arises along to.",
      },
      {
        id: 4,
        srcOne: require("@/assets/blog/blog-4.jpg"),
        srcTwo: require("@/assets/blog/blog-4-2.jpg"),
        date: "May 6, 2023",
        title: "How to Choose the Perfect Palette for Your Home",
        link: "how-to-choose-the-perfect-palette-for-your-home",
        para: "Ask a quick six seven offer see among. Handsome met debating sir dwelling age material.",
      },
      {
        id: 5,
        srcOne: require("@/assets/blog/blog-5.jpg"),
        srcTwo: require("@/assets/blog/blog-5-2.jpg"),
        date: "Oct 21, 2023",
        title: "Simplifying Your Home for a Clutter-Free Life",
        link: "simplifying-your-home-for-a-clutter-free-life",
        para: "State burst think end are its. Arrived off she elderly beloved him affixed noisier yet.",
      },
      {
        id: 6,
        srcOne: require("@/assets/blog/blog-6.jpg"),
        srcTwo: require("@/assets/blog/blog-6-2.jpg"),
        date: "Dec 5, 2023",
        title: "How to Incorporate High-End Design on a Budget",
        link: "how-to-incorporate-high-end-design-on-a-budget",
        para: "Mr feeling chiefly cordial in do. Water timed folly right aware if oh truth.",
      },
      {
        id: 7,
        srcOne: require("@/assets/blog/blog-7.jpg"),
        srcTwo: require("@/assets/blog/blog-7-2.jpg"),
        date: "Jun 18, 2023",
        title: "Incorporating Retro and Antique Pieces into Modern Design",
        link: "incorporating-retro-and-antique-pieces-into-modern-design",
        para: "Unaffected at ye of compliment alteration to. Place voice no arises along to.",
      },
      {
        id: 8,
        srcOne: require("@/assets/blog/blog-8.jpg"),
        srcTwo: require("@/assets/blog/blog-8-2.jpg"),
        date: "Nov 10, 2023",
        title: "A Guide to Creating Cohesive Interior Design",
        link: "a-guide-to-creating-cohesive-interior-design",
        para: "Handsome met debating sir dwelling age material. As style lived he worse dried.",
      },
      {
        id: 9,
        srcOne: require("@/assets/blog/blog-9.jpg"),
        srcTwo: require("@/assets/blog/blog-9-2.jpg"),
        date: "Mar 3, 2023",
        title: "Simple and Inexpensive Ways to Update Your Office Decor",
        link: "simple-and-inexpensive-ways-to-update-your-office-decor",
        para: "Handsome met debating sir dwelling age material. As style lived he worse dried.",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
